name: Run The Tests

on:
    push:
        branches:
            - main

pull_request:
    branches: - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: action/checkout@v2
            - name: Set up Python 3.12.2
              uses: actions/setup-python@v2
              with:
                  python-version: 3.12.2
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Unit Testing
              run: |
                  cd ciphers_project
                  python manage.py test
            - name: Build and push the image
                run: |
                    docker login --username sierranapieralski --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                    docker build -t ghcr.io/sierranapieralski/ciphers-service:latest --file Dockerfile .
                    docker push ghcr.io/sierranapieralski/ciphers-service:latest  
